FROM node:19.4-alpine3.16

RUN mkdir server

WORKDIR /server

ENV MONGODB_URI=mongodb://mongoDB:27017/mybus-db

ENV NODE_ENV=development

ENV TOKEN_KEY=B3C0NBUS!N3GR0UP

ENV PORT=5000

ENV HOST=localhost

COPY ./package.json yarn.lock ./

RUN yarn

COPY . .

CMD ["yarn","start"]